language: go

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx


matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

branches:
    only:
    - master

script:
  - if [ -n "$(gofmt -s -l . | grep -v "vendor")" ]; then diff -u <(echo -n) <(gofmt -d $(gofmt -s -l . | grep -v "vendor")); fi
  - go test -v -race -coverprofile=coverage.txt  $(go list ./... | grep -v "/vendor/")

after_success:
  - bash <(curl -s https://codecov.io/bash)
